services:
  spotdl-sync:
    image: ghcr.io/woliver99/spotdl-sync:main
    container_name: spotdl-sync
    restart: always
    environment:
      - PLAYLIST_URL=YOUR_PLAYLIST_URL_HERE
      - SYNC_INTERVAL_SECONDS=10800
      - SYNC_DIRECTORY=/music

      - SPOTIFY_CLIENT_ID=YOUR_CLIENT_ID_HERE
      - SPOTIFY_CLIENT_SECRET=YOUR_CLIENT_SECRET_HERE
    volumes:
      - ./my-synced-music:/music
      - ./my-synced-music/.spotdl:/root/.spotdl
